### ISSUE TITLE
The preamble isn't compatible with webpack (again)

### ISSUE THREAD

**Issue by lexaknyazev** [mbullington/node_preamble.dart#18]
As a part of `1.4.5` release, a new line was added at the beginning of the preamble:
https://github.com/mbullington/node_preamble.dart/blob/eedb58b0823f1e20b8c3d54eacd42843c81be9af/lib/preamble.js#L4

When building the resulting bundle, `webpack` tries to replace it with some boilerplate and fails when the polyfill for the `url` module is not available. The latter happens when `webpack` is invoked with node plugins disabled, see #15.

/cc @nex3

**Comment by mbullington** [comment]
I didn't check this closely enough, thanks for bringing this to my attention.

Will try & fix with `1.4.6` asap.

**Comment by mbullington** [comment]
@lexaknyazev Since this code isn't even run on browser when bundled, I could probably just move `require('url')` into the appropriate block and change it to `eval('require')('url')`. Other than this or modifying the Webpack config, I'm not sure of any other way to *prevent* bundling.

**Comment by lexaknyazev** [comment]
Just for context, why this line is needed?
It was added in #16, however `url` seems to be available in node's global scope even without `require`.

I don't think that packages can override webpack config of an app that uses them. `eval` might work although it would make compiled code incompatible with CSP.

**Comment by mbullington** [comment]
@lexaknyazev Right, I definitely want to be CSP friendly if possible. Also while `URL` is globally accessible (and `url` if you use the Node.js REPL), `url` isn't available globally for our script.

I wish you could do ala Browserify, where `require('url' + '')` was all you needed to prevent bundling.

Any ideas? @nex3

**Comment by lexaknyazev** [comment]
I see. `pathToFileURL` is a top-level function from node's `url` module, so it's unavailable without `require`.

> I wish you could do ala Browserify, where require('url' + '') was all you needed to prevent bundling.

webpack can evaluate some expressions, so the `require` call needs to be more complex, like:
```js
url = require(null == null ? 'url' : null);
```
However, webpack redirects all `require` calls to its own loader, so this line will fail when running processed code on node. 

To bypass this, yet another check is needed:
```js
url = "undefined" != typeof __non_webpack_require__ ? __non_webpack_require__('url') : require(null == null ? 'url' : null);
```

The latter seems to work in node with and without webpack (although minifiers can break it), but fails in the browser. This should not be a problem after moving this line to the appropriate block.

---

Given all these JS ecosystem conflicts, maybe it's time to integrate essential preamble parts into Dart compilers and/or build system?

**Comment by mbullington** [comment]
> I see. `pathToFileURL` is a top-level function from node's `url` module, so it's unavailable without `require`.
> 
> > I wish you could do ala Browserify, where require('url' + '') was all you needed to prevent bundling.
> 
> webpack can evaluate some expressions, so the `require` call needs to be more complex, like:
> 
> ```js
> url = require(null == null ? 'url' : null);
> ```
> 
> However, webpack redirects all `require` calls to its own loader, so this line will fail when running processed code on node.
> 
> To bypass this, yet another check is needed:
> 
> ```js
> url = "undefined" != typeof __non_webpack_require__ ? __non_webpack_require__('url') : require(null == null ? 'url' : null);
> ```
> 
> The latter seems to work in node with and without webpack (although minifiers can break it), but fails in the browser. This should not be a problem after moving this line to the appropriate block.

That's an absolutely absurd line, but thanks for doing your research! 👍 I'll do what you recommended.

> 
> Given all these JS ecosystem conflicts, maybe it's time to integrate essential preamble parts into Dart compilers and/or build system?

Also I agree. I'm not entirely sure what form this could take, but I'm very open to the idea.

**Comment by mbullington** [comment]
Closed with 1.4.7 :shipit:

**Comment by lexaknyazev** [comment]
The absurd `null == null ...` part got simplified in the minified version of the preamble.

**Comment by mbullington** [comment]
@lexaknyazev I changed how we minify files (using Terser.js locally instead of relying on an external website) and disabled simplifying conditionals. It comes out to be `require(1?'url':null)`.

I didn't want to publish again until I confirmed worked, could you please check out `1.4.8-test` and let me know if it works in your build environment?

Thanks!

**Comment by lexaknyazev** [comment]
Hi @mbullington,

Here's a much better workaround that seems to cover all issues mentioned above (shamelessly taken from the webpack's issue tracker):
```js
url = ("undefined" !== typeof __webpack_require__ ? __non_webpack_require__ : require)("url");
```

**Comment by mbullington** [comment]
Changed as of 1.4.8 🚢
