### ISSUE TITLE
Preamble is incompatible with Web Worker context

### ISSUE THREAD

**Issue by lexaknyazev** [mbullington/node_preamble.dart#19]
This check
https://github.com/mbullington/node_preamble.dart/blob/200335821627534bf35dc52d5a4e1d34b01b5a7e/lib/preamble.js#L34-L36

does not cover the case when a script is running inside browser's Web Worker thread. Therefore, it tries to call `require('url')` in browser context which is not an expected behavior.

While `self.document` is not available in the workers, Dart2JS runtime seems to be smart enough to work correctly in Worker context out of the box.

So, the preamble fix could look like this (replacing the quoted code above):
```js
if(!dartNodePreambleSelf.window && 
   !('undefined' !== typeof WorkerGlobalScope && dartNodePreambleSelf instanceof WorkerGlobalScope)) {
```

**Comment by mbullington** [comment]
Version v1.4.9 just published on pub should fix this issue. Please let me know, thanks!
