### ISSUE TITLE
Consider adding node detector

### ISSUE THREAD

**Issue by lexaknyazev** [mbullington/node_preamble.dart#5]
Some people may want to use dart2js-compiled library that has been published to npm, in the browser. So the full code pipeline would look like:
```
dart -> dart2js -> add_node_preamble -> publish_npm_package -> import_npm_package -> browserify
```

The resulting code will fail to run in the browser. This could be fixed like this:

```javascript
// Node.js detector adopted from https://github.com/iliakan/detect-node
if (Object.prototype.toString.call(typeof process !== 'undefined' ? process : 0) === '[object process]') {
  // insert current node_preamble here
} else {
  var self = global.self;
  self.exports = exports;
}
```

**Comment by mbullington** [comment]
Hi Alexey,

This makes sense to me, thank you for bringing it to my attention.

I'll try to dedicate some time this week to adding it.

**Comment by lexaknyazev** [comment]
Hi Michael,
have you had a chance to look into this?

I was able to workaround `browserify` issues when I was invoking `dart2js` manually, but it has become more difficult after transition to `package:build` (with `build_node_compilers`) because the preamble is being added automatically.

Thanks.

**Comment by mbullington** [comment]
Hi Alexey,

I've looked briefly at this issue, I'm still interested in adding support for this and I'm aware that I haven't upheld my original promise / timeline.

Thanks for your patience (and using the library), I'm going to look into this over the weekend and hopefully publish a new version on pub with the changes.

Thanks!

**Comment by mbullington** [comment]
Hi @lexaknyazev ,

I know you're using build_node_compilers, but are you able to test this PR for me? It should have all the features you requested, but I wanted to make sure it worked for your usecase before I published it to pub.

https://github.com/mbullington/node_preamble.dart/pull/12

Please let me know how it goes (and if you're able to test). Thanks!

**Comment by lexaknyazev** [comment]
Based on my initial tests, the updated preamble works fine with `browserify` in Chrome and Firefox, but it breaks async operations in MS Edge (Futures never complete).

I don't have a small repro atm, but I think I could make one in the meantime if it's needed.

**Comment by lexaknyazev** [comment]
I'm not sure what's the reason behind this, but changing
```js
var self = Object.create(global);
```
to 
```js
var self = global.self;
```
fixes Edge behavior.

Maybe, there could be a better fix for that.

**Comment by mbullington** [comment]
I'll have to find a Windows installation to look into this further, the problem I have with your fix is that it breaks encapsulation in a pretty big way.

So say you had Dart library a and b; if they both use the preamble without encapsulation, there's a non-zero chance that library b could be using library a's exports/require/etc functions. But re-declaring self in the local scope allows each package to have it's own globals (as should happen).

I wonder why Edge doesn't support this, maybe it has to do with setTimeout

**Comment by lexaknyazev** [comment]
You could use [free virtual machine images](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) with preinstalled Win10 to test on Edge.

**Comment by lexaknyazev** [comment]
@mbullington I think I've found a proper fix.

Here's a small repro with the same problem.
```javascript
function foo(global) {
    var self = Object.create(global);

    // setImmediate exists only in IE11, Edge, and node
    self.scheduleImmediate = self.setImmediate
        ? self.setImmediate
        : function (cb) {
            setTimeout(cb, 0);
        };

    // This line works in Chrome and Firefox but fails in Edge and IE11
    // with SCRIPT65535: Invalid calling object.
    self.scheduleImmediate(function () { console.log(42) });
}

foo(typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {});
```

Here's a fix:
```javascript
function foo(global) {
    var self = Object.create(global);

    // call [set*] functions from [global] explicitly
    self.scheduleImmediate = global.setImmediate
        ? function (cb) {
            global.setImmediate(cb);
        }
        : function (cb) {
            global.setTimeout(cb, 0);
        };

    // works everywhere
    self.scheduleImmediate(function () { console.log(42) });
}

foo(typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {});
```

**Comment by mbullington** [comment]
Great! That seems to work, I can understand why that's happening, but I wonder if anything else on Edge would be broken because of it...

Regardless that's probably a separate issue, thanks! (if there's any other discussion, there's also the PR).
